version: "3.8"

services:
  banners_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    entrypoint:
      - bash
      - "entrypoint.sh"
    env_file:
      - app/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - custom

  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - app/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - custom

#  redis:
#    image: redis:7.2.4-bookworm
#    ports:
#      - "6379:6379"
#    networks:
#      - custom

networks:
  custom:
    driver: bridge