version: "3.8"

services:
  banners_app:
    container_name: banners_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    command: "sh -c 'alembic upgrade head && uvicorn --factory application.main:create_app --reload --host 0.0.0.0 --port 8003'"
    env_file:
      - app/.env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app/:/app/


  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - app/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql


#  redis:
#    image: redis:7.2.4-bookworm
#    ports:
#      - "6379:6379"
#    networks:
#      - custom
